spring:
  application:
    name: sse-server


core:
  service:
    url: ${CORER_API_URL:http://localhost:9090}
    apiKey: ${CORE_SERVICE_API_KEY:change-me}

server:
  port: ${SERVER_PORT:9091}

nats:
  url: ${NATS_URL:nats://localhost:4222}
  notificationSubject: ${NATS_NOTIFICATION_SUBJECT:notifications}


