spring:
  application:
    name: sse-server


core:
  service:
    url: http://127.0.0.1:9090
    apiKey: svc-WpwFTAuPurE0L25O1YIhp1r9XSaOU7wl

server:
  port: ${SERVER_PORT:9091}

nats:
  url: ${NATS_URL:nats://localhost:4222}
  notificationSubject: ${NATS_NOTIFICATION_SUBJECT:notifications}


